name = "Innerpack"
author = "renavi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7912e803d2e89c1dd5e4d1a0899da0083d2b4f0719b33b8f00635b4a261e46c8"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
