name = "Innerpack"
author = "renavi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06b83c6cf424c3200e98afff910d14b146decbb3f5190dcf69c3ebc726ab1426"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
