name = "Innerpack"
author = "renavi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49629ea7346f3f786c1be6f63a3be6bc514eb606600658ba4e00a56aaf097b79"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
