name = "Innerpack"
author = "renavi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb5757eb042108a8637eae861c3eebeae5023e3f38600a99c56ce250761ab90c"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
